# Development environment using Cloudflare Wrangler
version: '3.8'

services:
  # Cloudflare Workers development server
  workers:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./edge/workers:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "8787:8787"
    command: |
      sh -c "
        npm install &&
        npm run dev -- --port 8787 --local
      "
    networks:
      - regctl

  # CLI development environment
  cli-dev:
    image: golang:1.23-alpine
    working_dir: /app
    volumes:
      - .:/app
      - go_modules:/go/pkg/mod
    environment:
      - REGCTL_API_URL=http://workers:8787
      - CGO_ENABLED=0
    command: |
      sh -c "
        apk add --no-cache git make &&
        cd cmd/regctl &&
        go run main.go
      "
    networks:
      - regctl
    profiles:
      - cli

  # Documentation server
  docs:
    image: python:3.11-alpine
    working_dir: /docs
    volumes:
      - ./site:/docs
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    networks:
      - regctl
    profiles:
      - docs

volumes:
  node_modules:
  go_modules:

networks:
  regctl:
    driver: bridge