name = "regctl-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespaces
kv_namespaces = [
  { binding = "SESSIONS", id = "03f57dba5a964634a495a0eaaa9868f1" },
  { binding = "CACHE", id = "75904cc15d75441b8b4fb33b0e0e5bc2" }
]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "regctl-db"
database_id = "1fd5a222-8923-4947-99c1-cb8defd90039"

# Durable Objects
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Queues
[[queues.producers]]
binding = "WEBHOOKS"
queue = "regctl-webhooks"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
APP_URL = "https://regctl-app.pages.dev"
VALUE_DOMAIN_API_KEY = "0LuCVBY2sy0LvKbTsDNB0NBa6zTfap0gSmHrANxT07WaCamHGZ9pydQwSVzn3ruWGFqRas99VBBfbsBz1FsDxgFFmA6f2Y4UbMU4"

# Routes - Updated for regctl.com domain
routes = [
  "api.regctl.com/*",
  "regctl.com/api/*",
  # Keep cloud routes for backward compatibility during transition
  "api.regctl.cloud/*",
  "regctl.cloud/api/*"
]

# Development
[env.development]
vars = { ENVIRONMENT = "development" }

# Staging
[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = ["staging-api.regctl.cloud/*"]